<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; // Add this line


class BooksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('books')->insert([
            [
                "title" => "god i see you",
                "author" => "monkey pen",
                "genre" => "English",
                "publication_year" => 2020,
                "isbn" => "ISBN 1135633762213",
                "pdf_file" => "GOD SEES YOU EVERYWHERE.pdf",
                "cover_image" => "EngImgs/god i see youغلاف.jpg",
                "description" => "هي قصة الطالب الذكي الذي يعتبر اذكى طالب في مدرسته هذه القصة هي اصغر قصة في القصص السابقة وكذلك تحتوي على بعض الكلمات السهلة",
            ],
            [
                "title" => "Bully Bill",
                "author" => "monkey pen",
                "genre" => "English",
                "publication_year" => 2020,
                "isbn" => "ISBN 21134536575447",
                "pdf_file" => "BULLY BILL.pdf",
                "cover_image" => "EngImgs/غلاف bully bill.jpg",
                "description" => "هي رواية انجليزية للاطفال تدور احداثها حول مزرعة يوجد بها خروف مغرور يعتقد انه هو القوي فيها لكن غروره لم يدم طويلا وسرعان ما تعلم درسا لن ينساه أبدا",
            ],
            [
                "title" => "one by Two",
                "author" => "monkey pen",
                "genre" => "English",
                "publication_year" => 2020,
                "isbn" => "ISBN 3661180534422",
                "pdf_file" => "one by two.pdf",
                "cover_image" => "EngImgs/غلاف one by Two.jpg",
                "description" => "هي قصة انجليزية قصيرة للأطفال، تدور أحداثها حول مشاركة واحد بأثنان أي مشاركة الطعام بشكل متساوي بين الصديقين",
            ],
            [
                "title" => "the case of the missing smile",
                "author" => "monkey pen",
                "genre" => "English",
                "publication_year" => 2020,
                "isbn" => "ISBN 1114636426543",
                "pdf_file" => "THE CASE OF THE MISSING SMILE.pdf",
                "cover_image" => "EngImgs/غلاف the case of the missing smile.jpg",
                "description" => "يحاول المحقق بيترسون العثور على المكان الذي فقدت فيه سالي سو ابتسامتها الجميلة. وتجده.. في قلبها، مخفيًا عن الأنظار",
            ],
            [
                "title" => "Lion king",
                "author" => "monkey pen",
                "genre" => "English",
                "publication_year" => 2020,
                "isbn" => "ISBN 5611483642335",
                "pdf_file" => "lion King.pdf",
                "cover_image" => "EngImgs/غلاف the lion king.jpg",
                "description" => "تحكي احداث متنوعة تدور حول الأسد الصغير سامبا ومغاملراته وسط الغابة مع والديه وباقي الحيوانات، 
                "
            ],
            [
                "title" => "the way of the Woods",
                "author" => " monkey pen",
                "genre" => "English",
                "publication_year" =>2020,
                "isbn" => "ISBN 11257833529745",
                "pdf_file" => "THE WAY OF THE WOODS.pdf",
                "cover_image" => "EngImgs/غلاف the way of the Woods.jpg",
                "description" => "  قصة لاتنسى عن الصداقة مع شخصيات مبهجة مثل الدب باو باو والكلب ديلارد و ابن عرس ويلارد
                "
            ],
            [
                "title" => "الرثاء",
                "author" => "ابي تمام والحتري",
                "genre" => "Literature",
                "publication_year" => 2010,
                "isbn" => "ISBN 1",
                "pdf_file" => "الرثاء بين ابي تمام والحتري والمتنبي.pdf",
                "cover_image" => "litImgs/غلاف الرثاء.jpg",
                "description" => "رسالة اجتازت مؤلفتها امتحان شهادة الآداب العليا بالجامعة السورية سنة ١٩٣٢",
            ],
            [
                "title" => "بتنا",
                "author" => "فتاة",
                "genre" => "Literature",
                "publication_year" => 2012,
                "isbn" => "ISBN 2",
                "pdf_file" => "بتنا - فتاة تحت سماء سيول.pdf",
                "cover_image" => "litImgs/غلاف بتنا.jpg",
                "description" => "الناس في نهاية المطاف انعكاس للمدينة",
            ],
            [
                "title" => "غلاف حصيلة الايام",
                "author" => "علي مولا",
                "genre" => "Literature",
                "publication_year" => 2012,
                "isbn" => "ISBN 3",
                "pdf_file" => "book.pdf",
                "cover_image" => "litImgs/غلاف حصيلة الايام.jpg",
                "description" => "كل حياة من الممكن أن تروى كرواية, وكل واحد منّا هو بطل أسطورته المخصصة",
            ],
            [
                "title" => "علي السنفود",
                "author" => "علي",
                "genre" => "Literature",
                "publication_year" => 2012,
                "isbn" => "ISBN 4",
                "pdf_file" => "على السفود .pdf",
                "cover_image" => "litImgs/غلاف على السفود.jpg",
                "description" => "جُمعت هذه المقالات في هذا الكتاب لتلقي الضوء على أسلوب من أساليب النقد الأدبي.",
            ],
            [
                "title" => "فردقان",
                "author" => "يوسف زيدان",
                "genre" => "Literature",
                "publication_year" => 2012,
                "isbn" => "ISBN 5",
                "pdf_file" => "فردقان ل يوسف زيدان.pdf",
                "cover_image" => "litImgs/غلاف فردقان.jpg",
                "description" => "تدور أحداث الرواية حول حياة ابن سينا في فترة اعتقاله بقلعة",
            ],
            [
                "title" => "محاضرات",
                "author" => "إبراهيم زيدان",
                "genre" => "Literature",
                "publication_year" => 2012,
                "isbn" => "ISBN 6",
                "pdf_file" => "محاضرات الادباء ومحاورات الشعراء.pdf",
                "cover_image" => "litImgs/غلاف محاضرات الادباء.jpg",
                "description" => "كان الكتاب موسوعياً غنياً بالشفافية الأدبية والذوق الشعري",
            ],
            [
                "title" => "خوف",
                "author" => "اسامة المسلم",
                "genre" => "Novel",
                "publication_year" => 2015,
                "isbn" => "9786030167616",
                "pdf_file" => "خوف.pdf",
                "cover_image" => "talesImgs/غلاف خوف.jpg",
                "description" => "تذكر قبل ان تدخل انك لن تخرج",
            ],
            [
                "title" => "أرسس",
                "author" => "احمد ال حمدان",
                "genre" => "Novel",
                "publication_year" => 2023,
                "isbn" => "9786038403297",
                "pdf_file" => "ارسس.pdf",
                "cover_image" => "talesImgs/غلاف ارسس.jpg",
                "description" => "اذا كنت غير مستعد للحقيقة لا تقرأ الرواية",
            ],
            [
                "title" => "الرعب في امتيفيل",
                "author" => "جاي انسون",
                "genre" => "Novel",
                "publication_year" => 2019,
                "isbn" => "9789777812504",
                "pdf_file" => "الرعب في امتيفيل.pdf",
                "cover_image" => "talesImgs/غلاف الرعب في امتيفيل.jpg",
                "description" => "اعلنت العائلة حان الوقت اخيرا كي يعرف العالم قصتهم",
            ],
            [
                "title" => "الذئب والمراقب",
                "author" => "نكلاس نات او داغ",
                "genre" => "Novel",
                "publication_year" => 2022,
                "isbn" => "9789776972292",
                "pdf_file" => "الذئب والمراقب.pdf",
                "cover_image" => "talesImgs/غلاف الذئب والمراقب.jpg",
                "description" => "الشر يفضي الى الشر والعنف يفضي الى العنف.",
            ],
            [
                "title" => "بعد حلول الظلام",
                "author" => "ايه جاين بارنز",
                "genre" => "Novel",
                "publication_year" => 2023,
                "isbn" => "9789779921044",
                "pdf_file" => "بعد حلول الظلام .pdf",
                "cover_image" => "talesImgs/غلاف بعد حلول الظلام.jpg",
                "description" => "تنتهي حفلة الخطوبة بموت مفجع ومفاجئ لنكتشف ان جميع الضيوف يخفون اسرارا رهيبة.",
            ],
            [
                "title" => "طبيب الجريمة",
                "author" => "لارنست ويليام هورنوج",
                "genre" => "Novel",
                "publication_year" => 2012,
                "isbn" => "9781527332195",
                "pdf_file" => "طبيب_الجريمة.pdf",
                "cover_image" => "talesImgs/غلاف طبيب الجريمة.jpg",
                "description" => "تدور احداث الرواية حول الجندي السابق جون دولار الذي يتعافى من اصابة في الرأس اصيب بها اثناء خدمته في الجيش.",
            ],
            [
                "title" => "نقض مركزية المركز",
                "author" => "اوما نارين وساندرا هاردينج",
                "genre" => "Philosophy",
                "publication_year" => 2010,
                "isbn" => "ISBN 9781103527390",
                "pdf_file" => "نقض مركزية المركز.pdf",
                "cover_image" => "phyImgs/غلاف نقض مركزية المركز.jpg",
                "description" => "الفلسفة من اجل عالم متعدد الثقافات بعد استعماري ونسوي",
            ],
            [
                "title" => "تاريخ الفلسفة الغربية",
                "author" => "برتراند رسل",
                "genre" => "Philosophy",
                "publication_year" => 2012,
                "isbn" => "ISBN 5152490067329",
                "pdf_file" => "تاريخ الفلسفة الغربية.pdf",
                "cover_image" => "phyImgs/غلاف تاريخ الفلسفة الغربية.jpg",
                "description" => "الفلسفة الغربية ابتداء من الفلاسفة ما قبل السقراطيين الى بداية القرن العشرين",
            ],
            [
                "title" => "المثقفون",
                "author" => "بول جونسون",
                "genre" => "Philosophy",
                "publication_year" => 2012,
                "isbn" => "ISBN 1989203600285",
                "pdf_file" => "المثقفون.pdf",
                "cover_image" => "phyImgs/غلاف المثقفون.jpg",
                "description" => "وجه حافل بالتناقض الشديد بين المفكرين وكتاباتهم والجانب الاخلاقي الذي كانو عليه",
            ],
            [
                "title" => "وحدة الانسان",
                "author" => "ج.برونوفسكي",
                "genre" => "Philosophy",
                "publication_year" => 2015,
                "isbn" => "ISBN 1892639001634",
                "pdf_file" => "وحدة الانسان.pdf",
                "cover_image" => "phyImgs/غلاف وحدة الانسان.jpg",
                "description" => "الانسان كيان واحد يتناغم فيه السعي الى الحقيقة مع التحديق في افاق الخيال.",
            ],
            [
                "title" => "النفس ودماغها",
                "author" => "كارل بوبر",
                "genre" => "Philosophy",
                "publication_year" => 2018,
                "isbn" => "ISBN 1696200262837",
                "pdf_file" => "النفس_ودماغها.pdf",
                "cover_image" => "phyImgs/غلاف النفس ودماغها.jpg",
                "description" => "بات امرا ملحا الاجابة عن السؤال الابرز هل الانسان اله ام انه غاية في ذاته؟",
            ],
            [
                "title" => "فلسفة الاشياء الصغيرة",
                "author" => "فتحي المسكيني",
                "genre" => "Philosophy",
                "publication_year" => 2012,
                "isbn" => "ISBN 9110367280028",
                "pdf_file" => "فلسفة الاشياء الصغيرة.pdf",
                "cover_image" => "phyImgs/غلاف فلسفة الاشياء الصغيرة.jpg",
                "description" => "باي معنى نقول عن شيء ما انه اكبر او اصغر من شي اخر؟",
            ],
            [
                "title" => "القوانين اليومية",
                "author" => "روبرت غرين",
                "genre" => "Self Development",
                "publication_year" => 2023,
                "isbn" => "ISBN 0236512330887",
                "pdf_file" => "القوانين اليومية.pdf",
                "cover_image" => "SelfDev/غلاف القوانين اليومية.jpg",
                "description" => "القاء اللوم على الاخرين في مشاكلنا عندما تكون المشكلة بداخلنا نابعة من سذاجتنا",
            ],
            [
                "title" => "الامتنان",
                "author" => "لويز هاي",
                "genre" => "Self Development",
                "publication_year" => 2008,
                "isbn" => "ISBN 3201547863201",
                "pdf_file" => "الامتنان.pdf",
                "cover_image" => "SelfDev/غلاف الامتنان.jpg",
                "description" => "كلما زاد شعور المء بالامتنان زاد الخير الذي يحصل عليه",
            ],
            [
                "title" => "الوعي الكلي",
                "author" => "اد هاليويل",
                "genre" => "Self Development",
                "publication_year" => 2014,
                "isbn" => "ISBN 2546985234759",
                "pdf_file" => "الوعي الكلي.pdf",
                "cover_image" => "SelfDev/غلاف الوعي الكلي.jpg",
                "description" => "كيف تحيا حياة رغيدة عن طريق الانتباه",
            ],
            [
                "title" => "مداواة جراحك",
                "author" => "بيفرلي اينجل",
                "genre" => "Self Development",
                "publication_year" => 2022,
                "isbn" => "ISBN 5632104500126",
                "pdf_file" => "مداواة جراحك.pdf",
                "cover_image" => "SelfDev/heal.jpg",
                "description" => "كيف يصوغ ابواك احترامك لذاتك وصورة ذاتك وصورة جسدك.",
            ],
            [
                "title" => "التغيير للافضل",
                "author" => "فريق اخضر",
                "genre" => "Self Development",
                "publication_year" => 2021,
                "isbn" => "ISBN 0012558741964",
                "pdf_file" => "التغيير للافضل.pdf",
                "cover_image" => "SelfDev/غلاف التغيير للافضل.jpg",
                "description" => "هل تشعر بأنك تتصرف بطرق غير مفهومة وتكرر اخطائك؟",
            ],
            [
                "title" => "القراءة الجامحة",
                "author" => "دونالين ميلر وسوزان كيلي",
                "genre" => "Self Development",
                "publication_year" => 2017,
                "isbn" => "ISBN 5514698456320",
                "pdf_file" => "القراءة الجامحة.pdf",
                "cover_image" => "SelfDev/غلاف القراءة الجامحة.jpg",
                "description" => "دليل لكل معلم يريد ان يزرع في طلابه عادات القراءة",
            ],
            [
                "title" => "عادات الشعوب وتقاليدها",
                "author" => "اديب ابي ضاهر",
                "genre" => "Social service",
                "publication_year" => 1993,
                "isbn" => "ISBN 3435363786543",
                "pdf_file" => "عادات الشعوب و تقاليدها.pdf",
                "cover_image" => "socialImgs/غلاف عادات الشعوب.jpg",
                "description" => "لكل شعب من شعوب العالم تقاليده وعاداته تميزه عن باقي الشعوب",
            ],
            [
                "title" => "الاقناع فن الفوز بما تريد",
                "author" => "ديف لاكاني",
                "genre" => "Social service",
                "publication_year" => 1817,
                "isbn" => "ISBN 3146853268567",
                "pdf_file" => "book.pdf",
                "cover_image" => "socialImgs/غلاف فن الاقناع.jpg",
                "description" => "كل انسان يريد ان تسير الامور على طريقته",
            ],
            [
                "title" => "الخوف من الحرية",
                "author" => "اريك فروم",
                "genre" => "Social service",
                "publication_year" => 1941,
                "isbn" => "ISBN 24334557538965",
                "pdf_file" => "خوف.pdf",
                "cover_image" => "socialImgs/غلاف الخوف من الحرية.jpg",
                "description" => "اذا لم اكن لنفسي فمن سيكون لي ؟",
            ],
            [
                "title" => "الفردوس الارضي",
                "author" => "عبد الوهاب المسيري",
                "genre" => "Social service",
                "publication_year" => 1979,
                "isbn" => "ISBN 2132465777786",
                "pdf_file" => "الفردوس الارضي.pdf",
                "cover_image" => "socialImgs/غلاف الفردوس الارضي.jpg",
                "description" => "يعيش الانسان جزاء من الطبيعة شأنه في شأن الكائنات العضوية الاخرى يولد ويموت.",
            ],
            [
                "title" => "عصر الفراغ",
                "author" => "جيل ليبوفتسكي",
                "genre" => "Social service",
                "publication_year" => 2018,
                "isbn" => "ISBN 2536479987656",
                "pdf_file" => "عصر الفراغ.pdf",
                "cover_image" => "socialImgs/عصر الفراغ.jpg",
                "description" => "ماذا عسانا نسمي هذا الموجة العارمة التي تميز عصرنا",
            ],
            [
                "title" => "اصنام المجتمع",
                "author" => "عبد الجليل الطاهر",
                "genre" => "Social service",
                "publication_year" => 2021,
                "isbn" => "ISBN 25364275894768",
                "pdf_file" => "اصنام المجتمع.pdf",
                "cover_image" => "socialImgs/غلاف اصنام المجتمع.jpg",
                "description" => "كيف انتشرت اليوم عبادة الاصنام وماهي الاسباب الداعية؟",
            ],
            
        ]);

    }
}
